# Generated by Django 3.2.14 on 2023-06-11 19:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('D', 'Desayuno'), ('A', 'Almuerzo'), ('C', 'Cena')], max_length=1)),
                ('ingredientes', models.TextField()),
                ('extra', models.TextField(blank=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('extra', models.TextField(blank=True)),
                ('comida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificador_comidas.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumpleanos', models.DateField(blank=True, null=True)),
                ('gustos', models.TextField(blank=True)),
                ('disgustos', models.TextField(blank=True)),
                ('extra', models.TextField(blank=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cumpleanos', models.DateField(default=datetime.datetime.today)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('comida_preferida', models.CharField(max_length=150)),
                ('gustos', models.TextField()),
                ('disgustos', models.TextField()),
                ('extra', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('F', 'Frescos'), ('S', 'Secos'), ('E', 'Enlatados'), ('Fr', 'Frutas'), ('V', 'Verduras'), ('C', 'Carne')], max_length=2)),
                ('precio_aprox', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_cantidad', models.CharField(choices=[('kg', 'Kilo'), ('unidad', 'Unidad'), ('g', 'Gramos'), ('l', 'Litros')], max_length=10)),
                ('extra', models.TextField(blank=True)),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificador_comidas.compra')),
            ],
        ),
        migrations.AddField(
            model_name='comida',
            name='miembros',
            field=models.ManyToManyField(related_name='comidas', to='planificador_comidas.Miembro'),
        ),
        migrations.AddField(
            model_name='comida',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
