# Generated by Django 4.2.1 on 2023-05-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=200, unique=True)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("D", "Desayuno"), ("A", "Almuerzo"), ("C", "Cena")],
                        max_length=1,
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                ("ingredientes", models.TextField()),
                ("extra", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("extra", models.TextField(blank=True)),
                (
                    "Comida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planificador_comidas.comida",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cumpleanos", models.DateField(blank=True, null=True)),
                ("gustos", models.TextField(blank=True)),
                ("disgustos", models.TextField(blank=True)),
                ("extra", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Miembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("edad", models.PositiveIntegerField()),
                ("comida_preferida", models.CharField(max_length=150)),
                ("gustos", models.TextField()),
                ("disgustos", models.TextField()),
                ("extra", models.TextField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planificador_comidas.perfil",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElementoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingrediente", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("F", "Frescos"),
                            ("S", "Secos"),
                            ("E", "Enlatados"),
                            ("Fr", "Frutas"),
                            ("V", "Verduras"),
                            ("C", "Carne"),
                        ],
                        max_length=2,
                    ),
                ),
                ("precio_aprox", models.DecimalField(decimal_places=2, max_digits=6)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "tipo_cantidad",
                    models.CharField(
                        choices=[
                            ("kg", "Kilo"),
                            ("unidad", "Unidad"),
                            ("g", "Gramos"),
                            ("l", "Litros"),
                        ],
                        max_length=10,
                    ),
                ),
                ("extra", models.TextField(blank=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planificador_comidas.compra",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comida",
            name="miembros",
            field=models.ManyToManyField(
                related_name="comidas", to="planificador_comidas.miembro"
            ),
        ),
        migrations.AddField(
            model_name="comida",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
