# Generated by Django 3.2.14 on 2023-05-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador_comidas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='Comida',
            new_name='comida',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='planificador_comidas.perfil'),
        ),
    ]
