# Generated by Django 3.2.14 on 2023-05-30 00:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificador_comidas', '0002_auto_20230523_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='fecha',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='miembro',
            name='cumpleanos',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='comida',
            name='fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='comida',
            name='inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
