# Generated by Django 3.2.14 on 2023-05-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificador_comidas', '0003_auto_20230529_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='perfil',
        ),
    ]
